import {auth,db,doc,getDoc,collection,query,where,onSnapshot,onAuthStateChanged,updateDoc} from './firebase-config.js';
const role=location.pathname.includes('driver')?'driver':'rider';
const section=document.createElement('section');section.className='card';section.style.cssText='background:white;padding:20px;margin:24px 0;border:1px solid #dbe3ee;border-radius:12px';
const heading=document.createElement('h2');heading.textContent=role==='rider'?'Rate your driver and add a tip':'Rate your riders';const message=document.createElement('p');message.setAttribute('role','status');const jobs=document.createElement('div');section.append(heading,message,jobs);document.querySelector('main').append(section);
let stop=null,generation=0;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
onAuthStateChanged(auth,async user=>{const check=++generation;stop?.();stop=null;jobs.replaceChildren();message.textContent='Sign in to review completed rides.';if(!user)return;try{const profile=await getDoc(doc(db,'users',user.uid));if(check!==generation||profile.data()?.role!==role)return;message.textContent='Loading completed rides...';stop=onSnapshot(query(collection(db,'rides'),where(role+'Id','==',user.uid)),snap=>{if(check!==generation)return;jobs.replaceChildren();const rides=snap.docs.map(d=>({...d.data(),id:d.id})).filter(r=>r.status==='completed').sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));message.textContent=rides.length?'Choose 1 to 5 stars. Ratings can be updated.':'No completed rides to review yet.';for(const ride of rides){const card=document.createElement('div');card.style.cssText='padding:16px 0;border-bottom:1px solid #e5e7eb';const title=document.createElement('p');title.textContent=(role==='rider'?ride.driverName:ride.riderName)+' | '+ride.pickup+' to '+ride.dropoff;
const label=document.createElement('label');label.textContent=role==='rider'?'Driver rating ':'Rider rating ';const rating=document.createElement('select');rating.innerHTML='<option value="">Choose rating</option>'+[1,2,3,4,5].map(n=>'<option value="'+n+'">'+n+' '+(n===1?'star':'stars')+'</option>').join('');rating.value=ride[role==='rider'?'driverRating':'riderRating']||'';label.append(rating);card.append(title,label);
let percent=null,custom=null,preview=null;
if(role==='rider'&&ride.fare!=null&&ride.pricingStatus!=='quote_required'){const tipLabel=document.createElement('label');tipLabel.style.marginLeft='16px';tipLabel.textContent='Tip ';percent=document.createElement('select');percent.innerHTML='<option value="0">No tip</option><option value="10">10%</option><option value="15">15%</option><option value="20">20%</option><option value="custom">Custom %</option>';const stored=Number(ride.tipPercent)||0;percent.value=[0,10,15,20].includes(stored)?String(stored):'custom';custom=document.createElement('input');custom.type='number';custom.min='0';custom.max='100';custom.step='0.1';custom.value=stored;custom.setAttribute('aria-label','Custom tip percentage');custom.style.width='90px';preview=document.createElement('p');function update(){custom.hidden=percent.value!=='custom';const p=percent.value==='custom'?Number(custom.value):Number(percent.value);const tip=Math.round(Number(ride.fare)*p)/100;preview.textContent='Tip: '+money(tip)+' | Rider total: '+money(Number(ride.fare)+tip)+' (recorded amount; no payment is charged here)';}percent.onchange=update;custom.oninput=update;update();tipLabel.append(percent,custom);card.append(tipLabel,preview);}
const save=document.createElement('button');save.type='button';save.textContent='Save review'+(percent?' and tip':'');save.style.margin='12px';const result=document.createElement('p');result.setAttribute('role','status');save.onclick=async()=>{if(auth.currentUser?.uid!==user.uid)return;if(!rating.value){result.textContent='Choose a rating from 1 to 5 stars.';return;}const values={[role==='rider'?'driverRating':'riderRating']:Number(rating.value)};if(percent){if(percent.value==='custom'&&(custom.value===''||!custom.reportValidity()))return;const p=percent.value==='custom'?Number(custom.value):Number(percent.value);values.tipPercent=p;values.tipAmount=Math.round(Number(ride.fare)*p)/100;values.totalFare=Math.round((Number(ride.fare)+values.tipAmount)*100)/100;}save.disabled=true;try{await updateDoc(doc(db,'rides',ride.id),values);result.textContent='Saved.';}catch(e){result.textContent=e.code==='permission-denied'?'Unable to save: check Firebase review permissions.':'Unable to save. Please retry.';}finally{save.disabled=false;}};card.append(save,result);jobs.append(card);}},()=>{message.textContent='Unable to load reviews. Check account approval and ride permissions.';});}catch{message.textContent='Unable to load your account.';}});
